const data = {
  lawsInPlay: [],
  factionCoordinates: {
    argent: {
      dd: ["1364,2236", "1376,2229"],
      ff: ["1610,2300"],
      sd: ["1366,2250"],
      cv: ["1464,2279"],
      pd: ["1514,2244"],
      gf: ["1545,2355", "1408,2274"],
    },
  },
  tileUnitData: {
    "210": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "211": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "310": {
      space: {
        argent: [
          { entityId: "ff", entityType: "unit", count: 2 },
          { entityId: "dd", entityType: "unit", count: 2 },
          { entityId: "cv", entityType: "unit", count: 1 },
        ],
      },
      planets: {
        ylir: {
          argent: [{ entityId: "pd", entityType: "unit", count: 1 }],
        },
        avar: {
          argent: [{ entityId: "gf", entityType: "unit", count: 2 }],
        },
        valk: {
          argent: [
            { entityId: "sd", entityType: "unit", count: 1 },
            { entityId: "gf", entityType: "unit", count: 3 },
          ],
        },
      },
      spaceTokens: [],
      planetTokens: {},
    },
    "212": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "311": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "312": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "313": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "314": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "315": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "316": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "317": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "318": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "000": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "101": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "102": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "201": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "103": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "202": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "301": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "104": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "203": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "302": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "105": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "204": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "303": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "106": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "205": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "304": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "206": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "305": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    tl: { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "207": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "306": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "208": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "307": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "209": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "308": { space: {}, planets: {}, spaceTokens: [], planetTokens: {} },
    "309": {
      space: {},
      planets: {},
      spaceTokens: ["token_frontier.png"],
      planetTokens: {},
    },
  },
  playerData: [
    {
      userName: "Meme Philosopher",
      faction: "argent",
      color: "red",
      displayName: "null",
      passed: false,
      eliminated: false,
      active: false,
      tacticalCC: 3,
      fleetCC: 3,
      strategicCC: 2,
      tg: 0,
      commodities: 0,
      commoditiesTotal: 3,
      crf: 0,
      hrf: 0,
      irf: 0,
      urf: 0,
      stasisInfantry: 0,
      actualHits: 0,
      expectedHitsTimes10: 0,
      unitsOwned: [
        "carrier",
        "argent_flagship",
        "spacedock",
        "argent_destroyer",
        "fighter",
        "dreadnought",
        "infantry",
        "cruiser",
        "pds",
        "argent_mech",
      ],
      followedSCs: [],
      unfollowedSCs: [],
      exhaustedSCs: [],
      promissoryNotesInPlayArea: [],
      techs: ["nm", "ps"],
      exhaustedTechs: [],
      factionTechs: ["ah", "swa2"],
      notResearchedFactionTechs: ["ah", "swa2"],
      planets: ["valk", "ylir", "avar"],
      exhaustedPlanets: [],
      exhaustedPlanetAbilities: [],
      fragments: [],
      relics: [],
      exhaustedRelics: [],
      leaders: [
        {
          id: "argentagent",
          type: "agent",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "argentcommander",
          type: "commander",
          tgCount: 0,
          exhausted: false,
          locked: true,
          active: false,
        },
        {
          id: "argenthero",
          type: "hero",
          tgCount: 0,
          exhausted: false,
          locked: true,
          active: false,
        },
      ],
      leaderIDs: ["argentagent", "argentcommander", "argenthero"],
      secretsScored: {},
      flexibleDisplayName: "Argent",
      scs: [],
      isSpeaker: true,
      neighbors: [],
      spaceArmyRes: 6.0,
      groundArmyRes: 2.5,
      spaceArmyHealth: 5.0,
      groundArmyHealth: 5.0,
      spaceArmyCombat: 1.2,
      groundArmyCombat: 1.5,
      soCount: 0,
      acCount: 0,
      pnCount: 6,
      unitCounts: {
        dd: { unitCap: 0, deployedCount: 2 },
        ff: { unitCap: 0, deployedCount: 1 },
        dn: { unitCap: 0, deployedCount: 0 },
        plenaryorbital: { unitCap: 0, deployedCount: 0 },
        monument: { unitCap: 0, deployedCount: 0 },
        fs: { unitCap: 0, deployedCount: 0 },
        sd: { unitCap: 0, deployedCount: 1 },
        cavalry: { unitCap: 0, deployedCount: 0 },
        cv: { unitCap: 0, deployedCount: 1 },
        pd: { unitCap: 0, deployedCount: 1 },
        lady: { unitCap: 0, deployedCount: 0 },
        mf: { unitCap: 0, deployedCount: 0 },
        ws: { unitCap: 0, deployedCount: 0 },
        ca: { unitCap: 0, deployedCount: 0 },
        gf: { unitCap: 0, deployedCount: 2 },
        tyrantslament: { unitCap: 0, deployedCount: 0 },
      },
      nombox: {},
    },
  ],
  tilePositions: [
    "000:18",
    "101:85a180",
    "102:85a240",
    "103:85a300",
    "104:73",
    "105:85a60",
    "106:85a120",
    "201:85a180",
    "202:84a",
    "203:85a240",
    "204:84a60",
    "205:85a300",
    "206:87a300",
    "207:60",
    "208:66",
    "209:85a60",
    "210:84a240",
    "211:85a120",
    "212:84a300",
    "301:85a180",
    "302:84a",
    "303:84a",
    "304:85a240",
    "305:84a60",
    "306:84a60",
    "307:85a300",
    "308:84a120",
    "309:42",
    "310:58",
    "311:68",
    "312:84a180",
    "313:85a60",
    "314:84a240",
    "315:84a240",
    "316:85a120",
    "317:84a300",
    "318:84a300",
    "tl:82a",
  ],
};
