export const gameState = {
  versionSchema: 4,
  lawsInPlay: [
    {
      id: "minister_industry",
      name: "Minister of Industry",
      uniqueId: 160,
      type: "Law",
      target: "Elect Player",
      text1:
        "The elected player gains this card. When the owner of this card places a space dock in a system, their units in that system may use their PRODUCTION abilities.",
      text2: "",
      mapText:
        "When you place a space dock in a system, your units in that system may use their PRODUCTION abilities.",
      electedInfo: "cabal",
      electedFaction: "cabal",
      electedType: "player",
      controlTokens: [],
      displaysElectedFaction: true,
    },
  ],
  statTilePositions: {
    hacan: ["405", "404", "406"],
    keleresm: ["413", "412", "414"],
    mahact: ["417", "416", "418"],
    argent: ["421", "420", "422"],
    yssaril: ["401", "402", "424"],
    cabal: ["409", "410", "408"],
  },
  strategyCards: [
    {
      initiative: 1,
      name: "Leadership",
      id: "pok1leadership",
      picked: false,
      played: false,
      exhausted: false,
      tradeGoods: 0,
      pickedByFaction: null,
    },
    {
      initiative: 2,
      name: "Diplomacy",
      id: "pok2diplomacy",
      picked: false,
      played: false,
      exhausted: false,
      tradeGoods: 2,
      pickedByFaction: null,
    },
    {
      initiative: 3,
      name: "Politics",
      id: "pok3politics",
      picked: false,
      played: false,
      exhausted: false,
      tradeGoods: 0,
      pickedByFaction: null,
    },
    {
      initiative: 4,
      name: "Construction",
      id: "pok4construction",
      picked: false,
      played: false,
      exhausted: false,
      tradeGoods: 0,
      pickedByFaction: null,
    },
    {
      initiative: 5,
      name: "Trade",
      id: "pok5trade",
      picked: false,
      played: false,
      exhausted: false,
      tradeGoods: 1,
      pickedByFaction: null,
    },
    {
      initiative: 6,
      name: "Warfare",
      id: "pok6warfare",
      picked: false,
      played: false,
      exhausted: false,
      tradeGoods: 0,
      pickedByFaction: null,
    },
    {
      initiative: 7,
      name: "Technology",
      id: "pok7technology",
      picked: false,
      played: false,
      exhausted: false,
      tradeGoods: 0,
      pickedByFaction: null,
    },
    {
      initiative: 8,
      name: "Imperial",
      id: "pok8imperial",
      picked: false,
      played: false,
      exhausted: false,
      tradeGoods: 0,
      pickedByFaction: null,
    },
  ],
  gameCustomName: "dsdsd",
  cardPool: {
    secretObjectiveDeck: [
      "mrm",
      "gamf",
      "faa",
      "ose",
      "fsn",
      "ans",
      "bam",
      "te",
      "mtm",
      "sb",
      "mew",
      "ttfd",
      "fwp",
      "ctr",
      "syc",
      "dp",
      "csl",
      "btv",
      "fwm",
      "dtd",
      "mp",
      "btgk",
      "otf",
    ],
    secretObjectiveFullDeckSize: 40,
    actionCardDeck: [
      "decisive_victory",
      "smuggler_routes",
      "freedom_fighters",
      "malfunction",
      "refabrication",
      "artifact_hunters",
      "exploration_rider",
      "ixthian_gift",
      "hijacked_signal",
      "direct_hit3_acd2",
      "micrometeoroid_storm",
      "sabotage1_acd2",
      "strategic_focus",
      "armament_rider",
      "classified_rider",
      "betrayal",
      "frontier_rider",
      "lost_treatise",
      "shrapnel_turrets",
      "shock_troops",
      "outmaneuver3",
      "overtime",
      "flawless_strategy",
      "defense_installation4",
      "joint_research",
      "public_outrage",
      "direct_hit1_acd2",
      "breakthrough",
      "war_machine1_acd2",
      "ancient_trade_routes",
      "relay_connection",
      "direct_hit2_acd2",
      "outmaneuver1",
      "stasis_haul",
      "espionage",
      "sabotage4_acd2",
      "deflection",
      "sabotage2_acd2",
      "classified_weapons_acd2",
      "short-lived_clone",
      "reengineer",
      "revolution",
    ],
    actionCardDiscard: [
      "outgun3",
      "side_project3",
      "hostile_world",
      "opportunists",
      "derelict_station",
      "retrofit",
      "corporate_lobbying",
      "defense_rider",
      "schematics_rider",
      "data_archive",
      "side_project1",
      "mysterious_brokers",
      "skilled_retreat2_acd2",
      "void_path",
      "tomb_raiders",
      "artifact_research",
      "rendezvous",
      "unexpected_strategy",
      "defense_installation3",
      "skilled_retreat3_acd2",
      "project_rider",
      "rehashed_debates",
      "special_considerations",
      "outgun2",
      "reconstruction",
      "patronage",
      "intrigue",
      "lazax_cache",
      "arms_deal",
      "defense_installation2",
      "covert_operation",
      "hidden_initiatives",
      "heist",
      "mercenary_contract",
      "stranded_ship",
      "syndicate",
      "skilled_retreat1_acd2",
      "efficiency_initiative",
      "pivot",
      "flank_speed2_acd2",
      "final_mission",
      "reinforcements",
      "stolen_prototype",
      "side_project2",
      "public_support",
    ],
    actionCardFullDeckSize: 120,
    culturalExploreDeck: ["crf8", "frln3", "crf3", "pw", "crf2"],
    culturalExploreDiscard: ["frln1", "frln2", "mo3", "mo2", "mo1"],
    culturalExploreFullDeckSize: 20,
    industrialExploreDeck: [
      "lf2",
      "cybernetic",
      "lf3",
      "aw2",
      "lf4",
      "lf1",
      "aw1",
      "irf3",
    ],
    industrialExploreDiscard: ["fb3", "aw3", "fb4", "fb1", "fb2", "aw4"],
    industrialExploreFullDeckSize: 20,
    hazardousExploreDeck: [
      "exp1",
      "hrf4",
      "vfs3",
      "hrf6",
      "hrf2",
      "hrf3",
      "warfare",
      "cm2",
      "hrf5",
    ],
    hazardousExploreDiscard: [
      "vfs2",
      "cm1",
      "exp2",
      "vfs1",
      "cm3",
      "exp3",
      "hrf1",
      "hrf7",
    ],
    hazardousExploreFullDeckSize: 20,
    frontierExploreDeck: [
      "lc2",
      "dv1",
      "ion",
      "lc1",
      "mirage",
      "ms1",
      "dw",
      "ent",
      "minent",
      "kel1",
    ],
    frontierExploreDiscard: ["ms2", "kel2", "majent", "dv2"],
    frontierExploreFullDeckSize: 20,
    relicDeck: [
      "dynamiscore",
      "emphidia",
      "dominusorb",
      "mawofworlds",
      "thalnos",
      "obsidian",
      "titanprototype",
      "emelpar",
      "shard",
    ],
    relicFullDeckSize: 16,
    agendaDeck: [
      "warrant",
      "minister_commrece",
      "minister_sciences",
      "conventions",
      "covert",
      "minister_exploration",
      "censure",
      "arms_reduction",
      "abolishment",
      "secret",
      "rep_govt",
      "cladenstine",
      "conscription",
      "disarmamament",
      "wormhole_recon",
      "committee",
      "arbiter",
      "revolution",
      "regulations",
      "minister_war",
      "prophecy",
      "incentive",
      "economic_equality",
      "minister_policy",
      "classified",
      "execution",
      "artifact",
      "checks",
      "plowshares",
      "mutiny",
      "nexus",
      "miscount",
      "minister_antiquities",
      "articles_war",
      "rearmament",
      "standardization",
      "seed_empire",
      "travel_ban",
      "sanctions",
      "defense_act",
      "redistribution",
      "minister_peace",
      "shared_research",
      "schematics",
      "wormhole_research",
      "constitution",
    ],
    agendaDiscard: ["grant_reallocation", "unconventional", "crisis"],
    agendaFullDeckSize: 50,
  },
  playerData: [
    {
      userName: "Tazingo",
      faction: "yssaril",
      color: "magma",
      displayName: "null",
      passed: false,
      eliminated: false,
      active: false,
      tacticalCC: 4,
      fleetCC: 3,
      strategicCC: 0,
      ccReinf: 9,
      tg: 1,
      commodities: 0,
      commoditiesTotal: 3,
      resources: 11,
      influence: 9,
      totResources: 11,
      totInfluence: 9,
      optimalResources: 5,
      optimalInfluence: 5,
      flexValue: 3,
      totOptimalResources: 5,
      totOptimalInfluence: 5,
      totFlexValue: 3,
      crf: 0,
      hrf: 0,
      irf: 0,
      urf: 0,
      stasisInfantry: 0,
      actualHits: 3,
      expectedHitsTimes10: 22,
      unitsOwned: [
        "carrier",
        "yssaril_mech",
        "spacedock",
        "fighter",
        "yssaril_flagship",
        "dreadnought",
        "destroyer",
        "infantry",
        "cruiser",
        "pds",
      ],
      followedSCs: [],
      unfollowedSCs: [],
      exhaustedSCs: [],
      promissoryNotesInPlayArea: ["wasp_an", "peach_sftt"],
      techs: ["nm", "amd", "det", "pa", "mi", "bs", "gd", "st"],
      exhaustedTechs: [],
      factionTechs: ["tp", "mi"],
      notResearchedFactionTechs: ["tp"],
      planets: ["retillion", "shalloq", "hopesend", "vegamajor", "vegaminor"],
      exhaustedPlanets: [],
      exhaustedPlanetAbilities: [],
      fragments: [],
      relics: ["enigmaticdevice"],
      exhaustedRelics: [],
      leaders: [
        {
          id: "yssarilagent",
          type: "agent",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "yssarilcommander",
          type: "commander",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
      ],
      leaderIDs: ["yssarilagent", "yssarilcommander"],
      secretsScored: { eap: 59 },
      knownUnscoredSecrets: { dyp: 748 },
      numUnscoredSecrets: 2,
      flexibleDisplayName: "Yssaril",
      scs: [],
      isSpeaker: false,
      neighbors: ["purple", "glacier", "red", "peach"],
      spaceArmyRes: 33.0,
      groundArmyRes: 12.0,
      spaceArmyHealth: 22.0,
      groundArmyHealth: 18.0,
      spaceArmyCombat: 5.4,
      groundArmyCombat: 5.1,
      soCount: 2,
      acCount: 9,
      pnCount: 4,
      totalVps: 5,
      numScoreableSecrets: 3,
      unitCounts: {
        dd: { unitCap: 0, deployedCount: 0 },
        ff: { unitCap: 0, deployedCount: 2 },
        dn: { unitCap: 0, deployedCount: 3 },
        plenaryorbital: { unitCap: 0, deployedCount: 0 },
        monument: { unitCap: 0, deployedCount: 0 },
        fs: { unitCap: 0, deployedCount: 0 },
        sd: { unitCap: 0, deployedCount: 2 },
        cavalry: { unitCap: 0, deployedCount: 0 },
        cv: { unitCap: 0, deployedCount: 4 },
        pd: { unitCap: 0, deployedCount: 4 },
        lady: { unitCap: 0, deployedCount: 0 },
        mf: { unitCap: 0, deployedCount: 3 },
        ws: { unitCap: 0, deployedCount: 0 },
        ca: { unitCap: 0, deployedCount: 2 },
        gf: { unitCap: 0, deployedCount: 5 },
        tyrantslament: { unitCap: 0, deployedCount: 0 },
      },
      nombox: {},
      sleeperTokensReinf: 0,
      ghostWormholesReinf: [],
      mahactEdict: [],
      debtTokens: {},
      abilities: ["stall_tactics", "scheming", "crafty"],
    },
    {
      userName: "forleafs",
      faction: "hacan",
      color: "peach",
      displayName: "null",
      passed: false,
      eliminated: false,
      active: false,
      tacticalCC: 2,
      fleetCC: 3,
      strategicCC: 1,
      ccReinf: 10,
      tg: 3,
      commodities: 0,
      commoditiesTotal: 6,
      resources: 15,
      influence: 14,
      totResources: 15,
      totInfluence: 14,
      optimalResources: 10,
      optimalInfluence: 8,
      flexValue: 3,
      totOptimalResources: 10,
      totOptimalInfluence: 8,
      totFlexValue: 3,
      crf: 0,
      hrf: 0,
      irf: 0,
      urf: 0,
      stasisInfantry: 0,
      actualHits: 4,
      expectedHitsTimes10: 44,
      unitsOwned: [
        "carrier",
        "hacan_mech",
        "spacedock",
        "dreadnought2",
        "fighter",
        "destroyer",
        "infantry",
        "cruiser",
        "hacan_flagship",
        "pds",
      ],
      followedSCs: [],
      unfollowedSCs: [],
      exhaustedSCs: [],
      promissoryNotesInPlayArea: ["magma_sftt"],
      techs: ["st", "amd", "pi", "det", "gd", "qdn", "dn2"],
      exhaustedTechs: [],
      factionTechs: ["qdn", "pm"],
      notResearchedFactionTechs: ["pm"],
      planets: [
        "arretze",
        "hercant",
        "kamdorn",
        "arnor",
        "lor",
        "tequran",
        "torkan",
        "vefutii",
        "qucenn",
      ],
      exhaustedPlanets: [],
      exhaustedPlanetAbilities: [],
      fragments: [],
      relics: ["stellarconverter", "prophetstears"],
      exhaustedRelics: [],
      leaders: [
        {
          id: "hacanagent",
          type: "agent",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "hacancommander",
          type: "commander",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
      ],
      leaderIDs: ["hacanagent", "hacancommander"],
      secretsScored: { lsc: 398, eh: 87 },
      numUnscoredSecrets: 1,
      flexibleDisplayName: "Hacan",
      scs: [],
      isSpeaker: false,
      neighbors: ["wasp", "glacier", "magma", "red"],
      spaceArmyRes: 28.5,
      groundArmyRes: 14.0,
      spaceArmyHealth: 17.0,
      groundArmyHealth: 20.0,
      spaceArmyCombat: 4.6,
      groundArmyCombat: 5.6,
      soCount: 1,
      acCount: 5,
      pnCount: 5,
      totalVps: 6,
      numScoreableSecrets: 3,
      unitCounts: {
        dd: { unitCap: 0, deployedCount: 0 },
        ff: { unitCap: 0, deployedCount: 3 },
        dn: { unitCap: 0, deployedCount: 3 },
        plenaryorbital: { unitCap: 0, deployedCount: 0 },
        monument: { unitCap: 0, deployedCount: 0 },
        fs: { unitCap: 0, deployedCount: 1 },
        sd: { unitCap: 0, deployedCount: 2 },
        cavalry: { unitCap: 0, deployedCount: 0 },
        cv: { unitCap: 0, deployedCount: 1 },
        pd: { unitCap: 0, deployedCount: 0 },
        lady: { unitCap: 0, deployedCount: 0 },
        mf: { unitCap: 0, deployedCount: 4 },
        ws: { unitCap: 0, deployedCount: 0 },
        ca: { unitCap: 0, deployedCount: 2 },
        gf: { unitCap: 0, deployedCount: 6 },
        tyrantslament: { unitCap: 0, deployedCount: 0 },
      },
      nombox: {},
      sleeperTokensReinf: 0,
      ghostWormholesReinf: [],
      mahactEdict: [],
      debtTokens: {},
      abilities: ["arbiters", "guild_ships", "master_of_trade"],
    },
    {
      userName: "Will",
      faction: "cabal",
      color: "wasp",
      displayName: "null",
      passed: false,
      eliminated: false,
      active: false,
      tacticalCC: 0,
      fleetCC: 3,
      strategicCC: 0,
      ccReinf: 13,
      tg: 2,
      commodities: 0,
      commoditiesTotal: 2,
      resources: 15,
      influence: 20,
      totResources: 15,
      totInfluence: 20,
      optimalResources: 12,
      optimalInfluence: 16,
      flexValue: 1,
      totOptimalResources: 12,
      totOptimalInfluence: 16,
      totFlexValue: 1,
      crf: 0,
      hrf: 0,
      irf: 0,
      urf: 0,
      stasisInfantry: 0,
      actualHits: 4,
      expectedHitsTimes10: 56,
      unitsOwned: [
        "cabal_mech",
        "carrier",
        "dreadnought2",
        "destroyer",
        "cabal_flagship",
        "infantry",
        "fighter2",
        "cabal_spacedock",
        "cruiser",
        "pds",
      ],
      followedSCs: [],
      unfollowedSCs: [],
      exhaustedSCs: [],
      promissoryNotesInPlayArea: ["glacier_sftt", "magma_an"],
      techs: ["sar", "dn2", "gd", "sr", "vtx", "da", "ff2"],
      exhaustedTechs: [],
      factionTechs: ["dt2", "vtx"],
      notResearchedFactionTechs: ["dt2"],
      planets: [
        "acheron",
        "rarron",
        "everra",
        "mallice",
        "xxehan",
        "dalbootha",
        "lodor",
        "arinam",
        "meer",
        "perimeter",
      ],
      exhaustedPlanets: [],
      exhaustedPlanetAbilities: [],
      fragments: [],
      relics: [],
      exhaustedRelics: [],
      leaders: [
        {
          id: "cabalagent",
          type: "agent",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "cabalcommander",
          type: "commander",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
      ],
      leaderIDs: ["cabalagent", "cabalcommander"],
      secretsScored: { dyp: 748 },
      numUnscoredSecrets: 2,
      flexibleDisplayName: "Cabal",
      scs: [],
      isSpeaker: false,
      neighbors: ["purple", "glacier", "red", "peach"],
      spaceArmyRes: 58.0,
      groundArmyRes: 10.5,
      spaceArmyHealth: 41.0,
      groundArmyHealth: 17.0,
      spaceArmyCombat: 12.6,
      groundArmyCombat: 4.9,
      soCount: 2,
      acCount: 4,
      pnCount: 2,
      totalVps: 6,
      numScoreableSecrets: 3,
      unitCounts: {
        dd: { unitCap: 0, deployedCount: 2 },
        ff: { unitCap: 0, deployedCount: 5 },
        dn: { unitCap: 0, deployedCount: 5 },
        plenaryorbital: { unitCap: 0, deployedCount: 0 },
        monument: { unitCap: 0, deployedCount: 0 },
        fs: { unitCap: 0, deployedCount: 1 },
        sd: { unitCap: 0, deployedCount: 3 },
        cavalry: { unitCap: 0, deployedCount: 0 },
        cv: { unitCap: 0, deployedCount: 4 },
        pd: { unitCap: 0, deployedCount: 1 },
        lady: { unitCap: 0, deployedCount: 0 },
        mf: { unitCap: 0, deployedCount: 2 },
        ws: { unitCap: 0, deployedCount: 0 },
        ca: { unitCap: 0, deployedCount: 3 },
        gf: { unitCap: 0, deployedCount: 6 },
        tyrantslament: { unitCap: 0, deployedCount: 0 },
      },
      nombox: { hacan: ["ca,1"], mahact: ["dn,1"] },
      sleeperTokensReinf: 0,
      ghostWormholesReinf: [],
      mahactEdict: [],
      debtTokens: {},
      abilities: ["devour", "amalgamation", "riftmeld"],
    },
    {
      userName: "Inco.N.Damus",
      faction: "keleresm",
      color: "red",
      displayName: "null",
      passed: false,
      eliminated: false,
      active: false,
      tacticalCC: 3,
      fleetCC: 4,
      strategicCC: 1,
      ccReinf: 7,
      tg: 0,
      commodities: 0,
      commoditiesTotal: 2,
      resources: 13,
      influence: 15,
      totResources: 13,
      totInfluence: 15,
      optimalResources: 8,
      optimalInfluence: 12,
      flexValue: 1,
      totOptimalResources: 8,
      totOptimalInfluence: 12,
      totFlexValue: 1,
      crf: 0,
      hrf: 0,
      irf: 0,
      urf: 0,
      stasisInfantry: 0,
      actualHits: 3,
      expectedHitsTimes10: 31,
      unitsOwned: [
        "keleres_mech",
        "spacedock",
        "fighter",
        "dreadnought",
        "carrier2",
        "destroyer",
        "infantry",
        "cruiser",
        "keleres_flagship",
        "pds",
      ],
      followedSCs: [],
      unfollowedSCs: [],
      exhaustedSCs: [],
      promissoryNotesInPlayArea: ["purple_sftt"],
      techs: ["st", "amd", "gd", "iihq", "asn", "sdn", "cv2", "fl"],
      exhaustedTechs: [],
      factionTechs: ["iihq", "asn"],
      notResearchedFactionTechs: [],
      planets: [
        "mollprimusk",
        "sakulag",
        "lazar",
        "rigeli",
        "rigelii",
        "rigeliii",
        "custodiavigilia",
        "mr",
      ],
      exhaustedPlanets: [],
      exhaustedPlanetAbilities: [],
      fragments: [],
      relics: [],
      exhaustedRelics: [],
      leaders: [
        {
          id: "keleresagent",
          type: "agent",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "kelerescommander",
          type: "commander",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
      ],
      leaderIDs: ["keleresagent", "kelerescommander"],
      secretsScored: { mlp: 919 },
      numUnscoredSecrets: 1,
      flexibleDisplayName: "Keleresm",
      scs: [],
      isSpeaker: false,
      neighbors: ["wasp", "purple", "magma", "peach"],
      spaceArmyRes: 28.0,
      groundArmyRes: 16.0,
      spaceArmyHealth: 18.0,
      groundArmyHealth: 26.0,
      spaceArmyCombat: 4.4,
      groundArmyCombat: 7.5,
      soCount: 1,
      acCount: 5,
      pnCount: 6,
      totalVps: 6,
      numScoreableSecrets: 3,
      unitCounts: {
        dd: { unitCap: 0, deployedCount: 0 },
        ff: { unitCap: 0, deployedCount: 3 },
        dn: { unitCap: 0, deployedCount: 1 },
        plenaryorbital: { unitCap: 0, deployedCount: 0 },
        monument: { unitCap: 0, deployedCount: 0 },
        fs: { unitCap: 0, deployedCount: 1 },
        sd: { unitCap: 0, deployedCount: 2 },
        cavalry: { unitCap: 0, deployedCount: 0 },
        cv: { unitCap: 0, deployedCount: 3 },
        pd: { unitCap: 0, deployedCount: 1 },
        lady: { unitCap: 0, deployedCount: 0 },
        mf: { unitCap: 0, deployedCount: 3 },
        ws: { unitCap: 0, deployedCount: 0 },
        ca: { unitCap: 0, deployedCount: 1 },
        gf: { unitCap: 0, deployedCount: 5 },
        tyrantslament: { unitCap: 0, deployedCount: 0 },
      },
      nombox: {},
      sleeperTokensReinf: 0,
      ghostWormholesReinf: [],
      mahactEdict: [],
      debtTokens: {},
      abilities: ["laws_order", "council_patronage", "the_tribuni"],
    },
    {
      userName: "Bleezy4sheezy",
      faction: "mahact",
      color: "purple",
      displayName: "null",
      passed: false,
      eliminated: false,
      active: false,
      tacticalCC: 2,
      fleetCC: 3,
      strategicCC: 2,
      ccReinf: 9,
      tg: 0,
      commodities: 0,
      commoditiesTotal: 3,
      resources: 7,
      influence: 6,
      totResources: 8,
      totInfluence: 8,
      optimalResources: 4,
      optimalInfluence: 5,
      flexValue: 0,
      totOptimalResources: 4,
      totOptimalInfluence: 7,
      totFlexValue: 0,
      crf: 0,
      hrf: 0,
      irf: 0,
      urf: 0,
      stasisInfantry: 0,
      actualHits: 3,
      expectedHitsTimes10: 31,
      unitsOwned: [
        "mahact_infantry",
        "mahact_flagship",
        "mahact_mech",
        "spacedock",
        "fighter",
        "dreadnought",
        "carrier2",
        "destroyer",
        "cruiser",
        "pds",
      ],
      followedSCs: [],
      unfollowedSCs: [],
      exhaustedSCs: [],
      promissoryNotesInPlayArea: ["red_sftt"],
      techs: ["pi", "bs", "st", "nm", "det", "gd", "cv2", "sr"],
      exhaustedTechs: [],
      factionTechs: ["cl2", "gr"],
      notResearchedFactionTechs: ["cl2", "gr"],
      planets: ["ixth", "ang", "primor", "mirage"],
      exhaustedPlanets: ["mirage"],
      exhaustedPlanetAbilities: [],
      fragments: [],
      relics: [],
      exhaustedRelics: [],
      leaders: [
        {
          id: "mahactagent",
          type: "agent",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "mahactcommander",
          type: "commander",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "mahacthero",
          type: "hero",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
      ],
      leaderIDs: ["mahactagent", "mahactcommander", "mahacthero"],
      secretsScored: {},
      numUnscoredSecrets: 3,
      flexibleDisplayName: "Mahact",
      scs: [],
      isSpeaker: true,
      neighbors: ["wasp", "glacier", "magma", "red"],
      spaceArmyRes: 15.0,
      groundArmyRes: 13.0,
      spaceArmyHealth: 7.0,
      groundArmyHealth: 18.0,
      spaceArmyCombat: 2.4,
      groundArmyCombat: 5.0,
      soCount: 3,
      acCount: 5,
      pnCount: 4,
      totalVps: 5,
      numScoreableSecrets: 3,
      unitCounts: {
        dd: { unitCap: 0, deployedCount: 1 },
        ff: { unitCap: 0, deployedCount: 1 },
        dn: { unitCap: 0, deployedCount: 1 },
        plenaryorbital: { unitCap: 0, deployedCount: 0 },
        monument: { unitCap: 0, deployedCount: 0 },
        fs: { unitCap: 0, deployedCount: 1 },
        sd: { unitCap: 0, deployedCount: 3 },
        cavalry: { unitCap: 0, deployedCount: 0 },
        cv: { unitCap: 0, deployedCount: 1 },
        pd: { unitCap: 0, deployedCount: 0 },
        lady: { unitCap: 0, deployedCount: 0 },
        mf: { unitCap: 0, deployedCount: 4 },
        ws: { unitCap: 0, deployedCount: 0 },
        ca: { unitCap: 0, deployedCount: 1 },
        gf: { unitCap: 0, deployedCount: 3 },
        tyrantslament: { unitCap: 0, deployedCount: 0 },
      },
      nombox: {},
      sleeperTokensReinf: 0,
      ghostWormholesReinf: [],
      mahactEdict: ["red", "glacier"],
      debtTokens: {},
      abilities: ["hubris", "edict", "imperia"],
    },
    {
      userName: "Bearded One",
      faction: "argent",
      color: "glacier",
      displayName: "null",
      passed: false,
      eliminated: false,
      active: false,
      tacticalCC: 2,
      fleetCC: 3,
      strategicCC: 1,
      ccReinf: 9,
      tg: 0,
      commodities: 0,
      commoditiesTotal: 3,
      resources: 11,
      influence: 13,
      totResources: 11,
      totInfluence: 13,
      optimalResources: 7,
      optimalInfluence: 8,
      flexValue: 3,
      totOptimalResources: 7,
      totOptimalInfluence: 8,
      totFlexValue: 3,
      crf: 0,
      hrf: 0,
      irf: 0,
      urf: 0,
      stasisInfantry: 0,
      actualHits: 1,
      expectedHitsTimes10: 12,
      unitsOwned: [
        "carrier",
        "argent_flagship",
        "spacedock",
        "fighter",
        "dreadnought",
        "infantry",
        "cruiser",
        "pds",
        "argent_destroyer2",
        "argent_mech",
      ],
      followedSCs: [],
      unfollowedSCs: [],
      exhaustedSCs: [],
      promissoryNotesInPlayArea: ["wasp_sftt"],
      techs: ["ps", "st", "sar", "gd", "ah", "swa2"],
      exhaustedTechs: [],
      factionTechs: ["ah", "swa2"],
      notResearchedFactionTechs: [],
      planets: [
        "valk",
        "ylir",
        "avar",
        "centauri",
        "gral",
        "starpoint",
        "quann",
        "newalbion",
        "vorhal",
      ],
      exhaustedPlanets: [],
      exhaustedPlanetAbilities: [],
      fragments: [],
      relics: [],
      exhaustedRelics: [],
      leaders: [
        {
          id: "argentagent",
          type: "agent",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "argentcommander",
          type: "commander",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
        {
          id: "argenthero",
          type: "hero",
          tgCount: 0,
          exhausted: false,
          locked: false,
          active: false,
        },
      ],
      leaderIDs: ["argentagent", "argentcommander", "argenthero"],
      secretsScored: { pem: 984 },
      numUnscoredSecrets: 2,
      flexibleDisplayName: "Argent",
      scs: [],
      isSpeaker: false,
      neighbors: ["wasp", "purple", "magma", "peach"],
      spaceArmyRes: 16.0,
      groundArmyRes: 19.5,
      spaceArmyHealth: 16.0,
      groundArmyHealth: 31.0,
      spaceArmyCombat: 5.0,
      groundArmyCombat: 8.9,
      soCount: 2,
      acCount: 5,
      pnCount: 6,
      totalVps: 4,
      numScoreableSecrets: 3,
      unitCounts: {
        dd: { unitCap: 0, deployedCount: 8 },
        ff: { unitCap: 0, deployedCount: 3 },
        dn: { unitCap: 0, deployedCount: 0 },
        plenaryorbital: { unitCap: 0, deployedCount: 0 },
        monument: { unitCap: 0, deployedCount: 0 },
        fs: { unitCap: 0, deployedCount: 0 },
        sd: { unitCap: 0, deployedCount: 3 },
        cavalry: { unitCap: 0, deployedCount: 0 },
        cv: { unitCap: 0, deployedCount: 1 },
        pd: { unitCap: 0, deployedCount: 2 },
        lady: { unitCap: 0, deployedCount: 0 },
        mf: { unitCap: 0, deployedCount: 4 },
        ws: { unitCap: 0, deployedCount: 0 },
        ca: { unitCap: 0, deployedCount: 1 },
        gf: { unitCap: 0, deployedCount: 9 },
        tyrantslament: { unitCap: 0, deployedCount: 0 },
      },
      nombox: {},
      sleeperTokensReinf: 0,
      ghostWormholesReinf: [],
      mahactEdict: [],
      debtTokens: {},
      abilities: ["raid_formation", "zeal"],
    },
    {
      userName: "Meme Philosopher",
      faction: "null",
      color: "null",
      displayName: "null",
      passed: false,
      eliminated: false,
      active: false,
      tacticalCC: 3,
      fleetCC: 3,
      strategicCC: 2,
      ccReinf: 16,
      tg: 0,
      commodities: 0,
      commoditiesTotal: 0,
      resources: 0,
      influence: 0,
      totResources: 0,
      totInfluence: 0,
      optimalResources: 0,
      optimalInfluence: 0,
      flexValue: 0,
      totOptimalResources: 0,
      totOptimalInfluence: 0,
      totFlexValue: 0,
      crf: 0,
      hrf: 0,
      irf: 0,
      urf: 0,
      stasisInfantry: 0,
      actualHits: 0,
      expectedHitsTimes10: 0,
      unitsOwned: [],
      followedSCs: [],
      unfollowedSCs: [],
      exhaustedSCs: [],
      promissoryNotesInPlayArea: [],
      techs: [],
      exhaustedTechs: [],
      factionTechs: [],
      notResearchedFactionTechs: [],
      planets: [],
      exhaustedPlanets: [],
      exhaustedPlanetAbilities: [],
      fragments: [],
      relics: [],
      exhaustedRelics: [],
      leaders: [],
      leaderIDs: [],
      secretsScored: {},
      numUnscoredSecrets: 0,
      flexibleDisplayName: "Null",
      scs: [],
      isSpeaker: false,
      neighbors: [],
      spaceArmyRes: 0.0,
      groundArmyRes: 0.0,
      spaceArmyHealth: 0.0,
      groundArmyHealth: 0.0,
      spaceArmyCombat: 0.0,
      groundArmyCombat: 0.0,
      soCount: 0,
      acCount: 0,
      pnCount: 0,
      totalVps: 0,
      numScoreableSecrets: 3,
      unitCounts: {
        dd: { unitCap: 0, deployedCount: 0 },
        ff: { unitCap: 0, deployedCount: 0 },
        dn: { unitCap: 0, deployedCount: 0 },
        plenaryorbital: { unitCap: 0, deployedCount: 0 },
        monument: { unitCap: 0, deployedCount: 0 },
        fs: { unitCap: 0, deployedCount: 0 },
        sd: { unitCap: 0, deployedCount: 0 },
        cavalry: { unitCap: 0, deployedCount: 0 },
        cv: { unitCap: 0, deployedCount: 0 },
        pd: { unitCap: 0, deployedCount: 0 },
        lady: { unitCap: 0, deployedCount: 0 },
        mf: { unitCap: 0, deployedCount: 0 },
        ws: { unitCap: 0, deployedCount: 0 },
        ca: { unitCap: 0, deployedCount: 0 },
        gf: { unitCap: 0, deployedCount: 0 },
        tyrantslament: { unitCap: 0, deployedCount: 0 },
      },
      nombox: {},
      sleeperTokensReinf: 0,
      ghostWormholesReinf: [],
      mahactEdict: [],
      debtTokens: {},
      abilities: [],
    },
  ],
  gameRound: 3,
  gameName: "pbd10046",
  tileUnitData: {
    "210": {
      space: {
        yssaril: [
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {},
      ccs: [],
      production: {},
      anomaly: false,
    },
    "211": {
      space: {
        argent: [
          { entityId: "ff", entityType: "unit", count: 1, sustained: null },
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        gral: {
          controlledBy: "argent",
          entities: {
            argent: [
              { entityId: "gf", entityType: "unit", count: 2, sustained: null },
            ],
          },
          commodities: null,
        },
        centauri: {
          controlledBy: "argent",
          entities: {
            neutral: [
              {
                entityId: "tombofemphidia",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
            ],
            argent: [
              { entityId: "gf", entityType: "unit", count: 2, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "310": {
      space: {
        keleresm: [
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
          { entityId: "ff", entityType: "unit", count: 5, sustained: null },
        ],
      },
      planets: {
        mollprimusk: {
          controlledBy: "keleresm",
          entities: {
            keleresm: [
              {
                entityId: "gf",
                entityType: "unit",
                count: 12,
                sustained: null,
              },
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { red: 6 },
      anomaly: false,
    },
    "212": {
      space: {
        argent: [
          { entityId: "ff", entityType: "unit", count: 2, sustained: null },
          { entityId: "dd", entityType: "unit", count: 2, sustained: null },
        ],
      },
      planets: {
        starpoint: {
          controlledBy: "argent",
          entities: {
            argent: [
              { entityId: "gf", entityType: "unit", count: 4, sustained: null },
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        newalbion: {
          controlledBy: "argent",
          entities: {
            argent: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { glacier: 6 },
      anomaly: false,
    },
    "311": {
      space: {},
      planets: {
        rigeli: {
          controlledBy: "keleresm",
          entities: {
            keleresm: [
              { entityId: "pd", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        rigelii: {
          controlledBy: "keleresm",
          entities: {
            keleresm: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        rigeliii: {
          controlledBy: "keleresm",
          entities: {
            keleresm: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "312": {
      space: {
        cabal: [
          { entityId: "ff", entityType: "unit", count: 1, sustained: null },
          { entityId: "fs", entityType: "unit", count: 1, sustained: null },
          { entityId: "dn", entityType: "unit", count: 2, sustained: null },
        ],
      },
      planets: {
        meer: {
          controlledBy: "cabal",
          entities: {
            neutral: [
              {
                entityId: "lazaxsurvivors",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
            ],
            cabal: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        arinam: {
          controlledBy: "cabal",
          entities: {
            neutral: [
              {
                entityId: "biotic",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
            ],
            cabal: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "313": {
      space: {},
      planets: {
        ixth: {
          controlledBy: "mahact",
          entities: {
            mahact: [
              { entityId: "mf", entityType: "unit", count: 2, sustained: null },
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "gf", entityType: "unit", count: 4, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { purple: 5 },
      anomaly: false,
    },
    "314": {
      space: {},
      planets: {
        ang: { controlledBy: "mahact", entities: {}, commodities: null },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "315": {
      space: {
        mahact: [
          { entityId: "fs", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {},
      ccs: [],
      production: {},
      anomaly: true,
    },
    "316": {
      space: {
        neutral: [
          {
            entityId: "mirage",
            entityType: "token",
            count: 1,
            sustained: null,
          },
        ],
        argent: [
          { entityId: "ff", entityType: "unit", count: 3, sustained: null },
          { entityId: "dd", entityType: "unit", count: 2, sustained: null },
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        mirage: {
          controlledBy: "mahact",
          entities: {
            mahact: [
              { entityId: "mf", entityType: "unit", count: 2, sustained: null },
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "gf", entityType: "unit", count: 2, sustained: null },
            ],
          },
          commodities: null,
        },
        ylir: {
          controlledBy: "argent",
          entities: {
            argent: [
              { entityId: "gf", entityType: "unit", count: 4, sustained: null },
              { entityId: "pd", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        avar: {
          controlledBy: "argent",
          entities: {
            argent: [
              { entityId: "gf", entityType: "unit", count: 4, sustained: null },
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        valk: {
          controlledBy: "argent",
          entities: {
            argent: [
              { entityId: "gf", entityType: "unit", count: 2, sustained: null },
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { purple: 3, glacier: 10 },
      anomaly: false,
    },
    "317": {
      space: {
        neutral: [
          { entityId: "gamma", entityType: "token", count: 1, sustained: null },
        ],
        argent: [
          { entityId: "dd", entityType: "unit", count: 3, sustained: null },
        ],
      },
      planets: {
        quann: {
          controlledBy: "argent",
          entities: {
            argent: [
              { entityId: "gf", entityType: "unit", count: 3, sustained: null },
              { entityId: "pd", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { glacier: 1 },
      anomaly: false,
    },
    "318": {
      space: {
        yssaril: [
          { entityId: "cv", entityType: "unit", count: 2, sustained: null },
          { entityId: "ff", entityType: "unit", count: 2, sustained: null },
        ],
      },
      planets: {
        hopesend: {
          controlledBy: "yssaril",
          entities: {
            yssaril: [
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "gf", entityType: "unit", count: 2, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { magma: 5 },
      anomaly: false,
    },
    "000": {
      space: {
        keleresm: [
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
          { entityId: "ff", entityType: "unit", count: 3, sustained: null },
        ],
      },
      planets: {
        mr: {
          controlledBy: "keleresm",
          entities: {
            keleresm: [
              { entityId: "gf", entityType: "unit", count: 5, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
            neutral: [
              {
                entityId: "custodiavigilia1",
                entityType: "token",
                count: 1,
                sustained: null,
              },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { red: 3 },
      anomaly: false,
    },
    "101": {
      space: {
        yssaril: [
          { entityId: "gf", entityType: "unit", count: 1, sustained: null },
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
          { entityId: "dn", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        vegamajor: {
          controlledBy: "yssaril",
          entities: {
            neutral: [
              {
                entityId: "dmz_large",
                entityType: "token",
                count: 1,
                sustained: null,
              },
              {
                entityId: "dmz",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
            ],
          },
          commodities: null,
        },
        vegaminor: {
          controlledBy: "yssaril",
          entities: {
            neutral: [
              {
                entityId: "dysonsphere",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
            ],
            yssaril: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 2, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "102": {
      space: {},
      planets: {
        vefutii: { controlledBy: "hacan", entities: {}, commodities: null },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "201": {
      space: {
        argent: [
          { entityId: "dd", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        vorhal: {
          controlledBy: "argent",
          entities: {
            argent: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "103": { space: {}, planets: {}, ccs: [], production: {}, anomaly: false },
    "202": {
      space: {
        hacan: [
          { entityId: "ff", entityType: "unit", count: 1, sustained: null },
          { entityId: "dn", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {},
      ccs: [],
      production: {},
      anomaly: true,
    },
    "301": {
      space: {
        yssaril: [
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
          { entityId: "dn", entityType: "unit", count: 2, sustained: null },
          { entityId: "ff", entityType: "unit", count: 8, sustained: null },
        ],
      },
      planets: {
        shalloq: {
          controlledBy: "yssaril",
          entities: {
            yssaril: [
              { entityId: "gf", entityType: "unit", count: 4, sustained: null },
              { entityId: "pd", entityType: "unit", count: 2, sustained: null },
            ],
          },
          commodities: null,
        },
        retillion: {
          controlledBy: "yssaril",
          entities: {
            yssaril: [
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "gf", entityType: "unit", count: 4, sustained: null },
              { entityId: "pd", entityType: "unit", count: 2, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { magma: 4 },
      anomaly: false,
    },
    "104": {
      space: {
        cabal: [
          { entityId: "ff", entityType: "unit", count: 6, sustained: null },
          { entityId: "dn", entityType: "unit", count: 1, sustained: null },
          { entityId: "dd", entityType: "unit", count: 1, sustained: null },
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        lodor: {
          controlledBy: "cabal",
          entities: {
            cabal: [
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "gf", entityType: "unit", count: 4, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { wasp: 5 },
      anomaly: true,
    },
    "203": {
      space: {
        neutral: [
          {
            entityId: "frontier",
            entityType: "token",
            count: 1,
            sustained: null,
          },
        ],
      },
      planets: {},
      ccs: [],
      production: {},
      anomaly: true,
    },
    "302": { space: {}, planets: {}, ccs: [], production: {}, anomaly: false },
    "105": {
      space: {
        mahact: [
          { entityId: "dd", entityType: "unit", count: 1, sustained: null },
          { entityId: "ff", entityType: "unit", count: 2, sustained: null },
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        primor: {
          controlledBy: "mahact",
          entities: {
            mahact: [
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "gf", entityType: "unit", count: 4, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { purple: 4 },
      anomaly: false,
    },
    "204": {
      space: {
        hacan: [
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {},
      ccs: [],
      production: {},
      anomaly: false,
    },
    "303": {
      space: {
        hacan: [
          { entityId: "ff", entityType: "unit", count: 5, sustained: null },
          { entityId: "fs", entityType: "unit", count: 1, sustained: null },
          { entityId: "dn", entityType: "unit", count: 2, sustained: null },
        ],
      },
      planets: {
        tequran: {
          controlledBy: "hacan",
          entities: {
            hacan: [
              { entityId: "gf", entityType: "unit", count: 6, sustained: null },
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 2, sustained: null },
            ],
            neutral: [
              {
                entityId: "miningworld",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
              {
                entityId: "nanoforge",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
            ],
          },
          commodities: null,
        },
        torkan: { controlledBy: "hacan", entities: {}, commodities: null },
      },
      ccs: [],
      production: { peach: 8 },
      anomaly: false,
    },
    "106": {
      space: {
        yssaril: [
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {},
      ccs: [],
      production: {},
      anomaly: true,
    },
    "205": {
      space: {},
      planets: {
        qucenn: {
          controlledBy: "hacan",
          entities: {
            hacan: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
            neutral: [
              {
                entityId: "propulsion",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
            ],
          },
          commodities: null,
        },
        rarron: { controlledBy: "cabal", entities: {}, commodities: null },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "304": {
      space: {
        hacan: [
          { entityId: "ff", entityType: "unit", count: 1, sustained: null },
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        arretze: {
          controlledBy: "hacan",
          entities: {
            hacan: [
              { entityId: "gf", entityType: "unit", count: 2, sustained: null },
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        kamdorn: {
          controlledBy: "hacan",
          entities: {
            hacan: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        hercant: { controlledBy: "hacan", entities: {}, commodities: null },
      },
      ccs: [],
      production: { peach: 4 },
      anomaly: false,
    },
    "206": {
      space: {
        cabal: [
          { entityId: "ff", entityType: "unit", count: 2, sustained: null },
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
          { entityId: "dn", entityType: "unit", count: 1, sustained: null },
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        perimeter: {
          controlledBy: "cabal",
          entities: {
            cabal: [
              { entityId: "gf", entityType: "unit", count: 3, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "305": {
      space: {},
      planets: {
        arnor: {
          controlledBy: "hacan",
          entities: {
            hacan: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
        lor: {
          controlledBy: "hacan",
          entities: {
            hacan: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    tl: {
      space: {
        cabal: [
          { entityId: "ff", entityType: "unit", count: 7, sustained: null },
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
          { entityId: "dn", entityType: "unit", count: 1, sustained: null },
          { entityId: "dd", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        mallice: {
          controlledBy: "cabal",
          entities: {
            cabal: [
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { wasp: 5 },
      anomaly: true,
    },
    "207": {
      space: {
        keleresm: [
          { entityId: "cv", entityType: "unit", count: 1, sustained: null },
          { entityId: "fs", entityType: "unit", count: 1, sustained: null },
          { entityId: "dn", entityType: "unit", count: 1, sustained: null },
          { entityId: "ff", entityType: "unit", count: 2, sustained: null },
        ],
      },
      planets: {
        sakulag: {
          controlledBy: "keleresm",
          entities: {
            keleresm: [
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "mf", entityType: "unit", count: 1, sustained: null },
            ],
            neutral: [
              {
                entityId: "richworld",
                entityType: "attachment",
                count: 1,
                sustained: null,
              },
            ],
          },
          commodities: null,
        },
        lazar: {
          controlledBy: "keleresm",
          entities: {
            keleresm: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { red: 5 },
      anomaly: false,
    },
    "306": {
      space: {},
      planets: {
        everra: { controlledBy: "cabal", entities: {}, commodities: null },
      },
      ccs: [],
      production: {},
      anomaly: true,
    },
    "208": {
      space: {
        mahact: [
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {},
      ccs: [],
      production: {},
      anomaly: false,
    },
    "307": {
      space: {
        cabal: [
          { entityId: "ff", entityType: "unit", count: 4, sustained: null },
          { entityId: "cv", entityType: "unit", count: 2, sustained: null },
          { entityId: "ca", entityType: "unit", count: 1, sustained: null },
        ],
      },
      planets: {
        acheron: {
          controlledBy: "cabal",
          entities: {
            cabal: [
              { entityId: "sd", entityType: "unit", count: 1, sustained: null },
              { entityId: "pd", entityType: "unit", count: 1, sustained: null },
              { entityId: "gf", entityType: "unit", count: 3, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: { wasp: 5 },
      anomaly: true,
    },
    "209": { space: {}, planets: {}, ccs: [], production: {}, anomaly: false },
    "308": {
      space: {},
      planets: {
        xxehan: { controlledBy: "cabal", entities: {}, commodities: null },
        dalbootha: {
          controlledBy: "cabal",
          entities: {
            cabal: [
              { entityId: "gf", entityType: "unit", count: 1, sustained: null },
            ],
          },
          commodities: null,
        },
      },
      ccs: [],
      production: {},
      anomaly: false,
    },
    "309": {
      space: {
        neutral: [
          { entityId: "gamma", entityType: "token", count: 1, sustained: null },
        ],
      },
      planets: {},
      ccs: [],
      production: {},
      anomaly: false,
    },
  },
  ringCount: 3,
  objectives: {
    stage1Objectives: [
      {
        key: "diversify",
        name: "Diversify Research",
        pointValue: 1,
        revealed: true,
        scoredFactions: ["hacan", "mahact", "keleresm", "cabal"],
        peekingFactions: [],
        factionProgress: {
          hacan: 2,
          keleresm: 2,
          mahact: 3,
          argent: 2,
          yssaril: 2,
          cabal: 2,
        },
        progressThreshold: 2,
        multiScoring: false,
      },
      {
        key: "make_history",
        name: "Make History",
        pointValue: 1,
        revealed: true,
        scoredFactions: [
          "yssaril",
          "keleresm",
          "cabal",
          "argent",
          "hacan",
          "mahact",
        ],
        peekingFactions: [],
        factionProgress: {
          hacan: 2,
          keleresm: 1,
          mahact: 3,
          argent: 1,
          yssaril: 2,
          cabal: 3,
        },
        progressThreshold: 2,
        multiScoring: false,
      },
      {
        key: "research_outposts",
        name: "Found Research Outposts",
        pointValue: 1,
        revealed: true,
        scoredFactions: ["yssaril", "keleresm", "mahact", "argent"],
        peekingFactions: [],
        factionProgress: {
          hacan: 1,
          keleresm: 2,
          mahact: 1,
          argent: 3,
          yssaril: 1,
          cabal: 2,
        },
        progressThreshold: 3,
        multiScoring: false,
      },
      {
        key: "lost_outposts",
        name: "Discover Lost Outposts",
        pointValue: 1,
        revealed: true,
        scoredFactions: ["mahact", "yssaril", "cabal", "hacan"],
        peekingFactions: [],
        factionProgress: {
          hacan: 2,
          keleresm: 1,
          mahact: 0,
          argent: 1,
          yssaril: 2,
          cabal: 2,
        },
        progressThreshold: 2,
        multiScoring: false,
      },
      {
        key: "amass_wealth",
        name: "Amass Wealth",
        pointValue: 1,
        revealed: true,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {
          hacan: 9,
          keleresm: 6,
          mahact: 6,
          argent: 6,
          yssaril: 7,
          cabal: 8,
        },
        progressThreshold: 9,
        multiScoring: false,
      },
    ],
    stage2Objectives: [
      {
        key: "UNREVEALED_6144",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_3542",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_5045",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_8278",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_3673",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
    ],
    customObjectives: [
      {
        key: "Custodian/Imperial",
        name: "Custodian/Imperial",
        pointValue: 1,
        revealed: true,
        scoredFactions: ["cabal", "keleresm"],
        peekingFactions: [],
        factionProgress: {
          hacan: 0,
          keleresm: 0,
          mahact: 0,
          argent: 0,
          yssaril: 0,
          cabal: 0,
        },
        progressThreshold: 0,
        multiScoring: true,
      },
    ],
    allObjectives: [
      {
        key: "diversify",
        name: "Diversify Research",
        pointValue: 1,
        revealed: true,
        scoredFactions: ["hacan", "mahact", "keleresm", "cabal"],
        peekingFactions: [],
        factionProgress: {
          hacan: 2,
          keleresm: 2,
          mahact: 3,
          argent: 2,
          yssaril: 2,
          cabal: 2,
        },
        progressThreshold: 2,
        multiScoring: false,
      },
      {
        key: "make_history",
        name: "Make History",
        pointValue: 1,
        revealed: true,
        scoredFactions: [
          "yssaril",
          "keleresm",
          "cabal",
          "argent",
          "hacan",
          "mahact",
        ],
        peekingFactions: [],
        factionProgress: {
          hacan: 2,
          keleresm: 1,
          mahact: 3,
          argent: 1,
          yssaril: 2,
          cabal: 3,
        },
        progressThreshold: 2,
        multiScoring: false,
      },
      {
        key: "research_outposts",
        name: "Found Research Outposts",
        pointValue: 1,
        revealed: true,
        scoredFactions: ["yssaril", "keleresm", "mahact", "argent"],
        peekingFactions: [],
        factionProgress: {
          hacan: 1,
          keleresm: 2,
          mahact: 1,
          argent: 3,
          yssaril: 1,
          cabal: 2,
        },
        progressThreshold: 3,
        multiScoring: false,
      },
      {
        key: "lost_outposts",
        name: "Discover Lost Outposts",
        pointValue: 1,
        revealed: true,
        scoredFactions: ["mahact", "yssaril", "cabal", "hacan"],
        peekingFactions: [],
        factionProgress: {
          hacan: 2,
          keleresm: 1,
          mahact: 0,
          argent: 1,
          yssaril: 2,
          cabal: 2,
        },
        progressThreshold: 2,
        multiScoring: false,
      },
      {
        key: "amass_wealth",
        name: "Amass Wealth",
        pointValue: 1,
        revealed: true,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {
          hacan: 9,
          keleresm: 6,
          mahact: 6,
          argent: 6,
          yssaril: 7,
          cabal: 8,
        },
        progressThreshold: 9,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_6144",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_3542",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_5045",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_8278",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "UNREVEALED_3673",
        name: "UNREVEALED",
        pointValue: 2,
        revealed: false,
        scoredFactions: [],
        peekingFactions: [],
        factionProgress: {},
        progressThreshold: 0,
        multiScoring: false,
      },
      {
        key: "Custodian/Imperial",
        name: "Custodian/Imperial",
        pointValue: 1,
        revealed: true,
        scoredFactions: ["cabal", "keleresm"],
        peekingFactions: [],
        factionProgress: {
          hacan: 0,
          keleresm: 0,
          mahact: 0,
          argent: 0,
          yssaril: 0,
          cabal: 0,
        },
        progressThreshold: 0,
        multiScoring: true,
      },
    ],
  },
  vpsToWin: 10,
  tilePositions: [
    "000:18",
    "101:74",
    "102:20",
    "103:47",
    "104:26",
    "105:65",
    "106:80",
    "201:63",
    "202:79",
    "203:43",
    "204:50",
    "205:29",
    "206:60",
    "207:31",
    "208:40",
    "209:39",
    "210:49",
    "211:34",
    "212:27",
    "301:15",
    "302:46",
    "303:28",
    "304:16",
    "305:36",
    "306:68",
    "307:54",
    "308:32",
    "309:48",
    "310:94new",
    "311:76",
    "312:37",
    "313:52",
    "314:61",
    "315:41",
    "316:58",
    "317:25",
    "318:66",
    "tl:82b",
  ],
};
