import type { DashboardResponse } from "./types";

export const mockDashboard: DashboardResponse = {
  profile: {
    userId: "278901234567890123",
    userName: "JStrong",
    tiglCurrentRank: "TIGL Gold",
    tiglLatestRankAtGameStart: "TIGL Silver",
    titles: {
      totalCount: 27,
      items: [
        {
          title: "Speaker Emeritus",
          count: 6,
          gameIds: ["pbd1732", "pbd1708", "pbd1684", "pbd1661", "pbd1602", "pbd1551"],
        },
        {
          title: "Trade Baron",
          count: 5,
          gameIds: ["pbd1732", "pbd1708", "pbd1650", "pbd1629", "pbd1577"],
        },
        {
          title: "War Machine",
          count: 4,
          gameIds: ["pbd1710", "pbd1673", "pbd1629", "pbd1560"],
        },
        {
          title: "Diplomat",
          count: 3,
          gameIds: ["pbd1708", "pbd1661", "pbd1602"],
        },
        {
          title: "Master Tactician",
          count: 2,
          gameIds: ["pbd1710", "pbd1684"],
        },
        {
          title: "Most Likely To Stall",
          count: 1,
          gameIds: ["pbd1551"],
        },
      ],
    },
    diceLuck: {
      actualHits: 842.0,
      expectedHits: 803.6,
      ratio: 1.0478,
    },
    insights: {
      activity: {
        totalTurns: 724,
        averageTurnTimeSeconds: 3987,
      },
      badges: [
        {
          key: "fleet_logistics",
          name: "Fleet Logistics",
          tier: "GOLD",
          description: "Maintains a rapid operational tempo across many turns.",
          primaryMetric: {
            label: "Average turn time",
            value: 3987.0,
            unit: "seconds",
          },
          requirements: [
            {
              label: "Tracked turns",
              current: 724.0,
              target: 60.0,
              unit: "turns",
              met: true,
            },
          ],
          summary: "Average turn speed across all tracked turns.",
          tierRuleText: "Legendary <30m, Gold <1h, Silver <2h",
        },
        {
          key: "from_the_brink",
          name: "From the Brink",
          tier: "SILVER",
          description: "Closes out razor-thin endgames when the table is at match point.",
          primaryMetric: {
            label: "Clutch wins",
            value: 3.0,
            unit: "count",
          },
          requirements: [
            {
              label: "Clutch wins",
              current: 3.0,
              target: 2.0,
              unit: "count",
              met: true,
            },
          ],
          summary: "Wins where at least one opponent was also near the finish line.",
          tierRuleText: "Legendary 6+, Gold 4+, Silver 2+",
        },
        {
          key: "galactic_endurance",
          name: "Galactic Endurance",
          tier: "GOLD",
          description: "Finishes marathon campaigns that run at least 180 days.",
          primaryMetric: {
            label: "Marathon finishes",
            value: 2.0,
            unit: "count",
          },
          requirements: [
            {
              label: "180+ day finished games",
              current: 2.0,
              target: 1.0,
              unit: "games",
              met: true,
            },
          ],
          summary: "Counts completed games lasting 180 days or longer.",
          tierRuleText: "Legendary 3+, Gold 2+, Silver 1+",
        },
        {
          key: "speakers_hand",
          name: "Speaker's Hand",
          tier: "SILVER",
          description: "Earns repeated diplomacy-oriented titles and table influence signals.",
          primaryMetric: {
            label: "Diplomacy signals",
            value: 11.0,
            unit: "count",
          },
          requirements: [
            {
              label: "Diplomacy signals",
              current: 11.0,
              target: 8.0,
              unit: "count",
              met: true,
            },
          ],
          summary: "Recognizes sustained council-and-trade identity from title history.",
          tierRuleText: "Legendary 25+, Gold 15+, Silver 8+",
        },
      ],
      favoredFactions: [
        { faction: "Mentak", gamesPlayed: 7, wins: 2, winPercent: 28.57 },
        { faction: "Naalu", gamesPlayed: 6, wins: 2, winPercent: 33.33 },
        { faction: "Mahact", gamesPlayed: 5, wins: 2, winPercent: 40.0 },
        { faction: "Titans of Ul", gamesPlayed: 4, wins: 1, winPercent: 25.0 },
        { faction: "Ghosts of Creuss", gamesPlayed: 4, wins: 0, winPercent: 0.0 },
      ],
    },
    aggregates: {
      ready: true,
      completedGamesHash: "84d3a05f9f6d6f6f26d2d859fd19f9e3b99566f0f71b2448",
      completedGameCount: 31,
      eligibleGameCount: 29,
      aggregatesVersion: 3,
      computedAtEpochMs: 1771812631453,
      completedGameIds: [
        "pbd1732", "pbd1710", "pbd1708", "pbd1684",
        "pbd1673", "pbd1661", "pbd1650", "pbd1629",
        "pbd1602", "pbd1577", "pbd1560", "pbd1551",
      ],
      techStats: {
        byTech: {
          "Gravity Drive": { gamesWithTech: 24, percentInEligibleGames: 82.76 },
          "Dreadnought II": { gamesWithTech: 19, percentInEligibleGames: 65.52 },
          "Fleet Logistics": { gamesWithTech: 16, percentInEligibleGames: 55.17 },
          "Assault Cannon": { gamesWithTech: 9, percentInEligibleGames: 31.03 },
          "Sling Relay": { gamesWithTech: 13, percentInEligibleGames: 44.83 },
        },
      },
      factionWinStats: {
        byFaction: {
          Mentak: 2,
          Naalu: 2,
          Mahact: 2,
          "Titans of Ul": 1,
          Arborec: 1,
          "Yin Brotherhood": 1,
        },
      },
      strategyCardStats: {
        bySc: {
          "1": { totalPicks: 34, gamesPicked: 22, winsInGamesPicked: 7, winRateWhenPicked: 31.82 },
          "2": { totalPicks: 29, gamesPicked: 19, winsInGamesPicked: 4, winRateWhenPicked: 21.05 },
          "3": { totalPicks: 27, gamesPicked: 17, winsInGamesPicked: 5, winRateWhenPicked: 29.41 },
          "4": { totalPicks: 31, gamesPicked: 20, winsInGamesPicked: 6, winRateWhenPicked: 30.0 },
          "5": { totalPicks: 22, gamesPicked: 15, winsInGamesPicked: 3, winRateWhenPicked: 20.0 },
          "6": { totalPicks: 28, gamesPicked: 18, winsInGamesPicked: 4, winRateWhenPicked: 22.22 },
          "7": { totalPicks: 25, gamesPicked: 16, winsInGamesPicked: 3, winRateWhenPicked: 18.75 },
          "8": { totalPicks: 30, gamesPicked: 21, winsInGamesPicked: 6, winRateWhenPicked: 28.57 },
        },
        meta: {
          completedGamesConsidered: 29,
          gamesWithRoundStats: 26,
        },
      },
      combatProfile: {
        totals: {
          combatsInitiated: 132,
          tacticalsWithCombat: 119,
          planetsTaken: 87,
          planetsStolen: 18,
          diceRolled: 2579,
        },
        averagesPerCompletedGame: {
          combatsInitiated: 4.55,
          tacticalsWithCombat: 4.1,
          planetsTaken: 3.0,
          planetsStolen: 0.62,
          diceRolled: 88.93,
        },
        coverage: {
          completedGamesConsidered: 29,
          gamesWithRoundStats: 26,
        },
      },
      economyProfile: {
        totalExpensesSum: 1942.5,
        avgTotalExpenses: 66.98,
        completedGamesConsidered: 29,
      },
      factionTechSynergy: {
        byFaction: {
          Mahact: {
            games: 5,
            wins: 2,
            nonWins: 3,
            byTech: {
              "Fleet Logistics": {
                gamesWithTech: 4,
                winsWithTech: 2,
                nonWinsWithTech: 2,
                winRateWhenTech: 50.0,
              },
              "Carrier II": {
                gamesWithTech: 3,
                winsWithTech: 1,
                nonWinsWithTech: 2,
                winRateWhenTech: 33.33,
              },
            },
          },
          Mentak: {
            games: 7,
            wins: 2,
            nonWins: 5,
            byTech: {
              "Dreadnought II": {
                gamesWithTech: 5,
                winsWithTech: 2,
                nonWinsWithTech: 3,
                winRateWhenTech: 40.0,
              },
              "Assault Cannon": {
                gamesWithTech: 4,
                winsWithTech: 1,
                nonWinsWithTech: 3,
                winRateWhenTech: 25.0,
              },
            },
          },
        },
      },
      speakerImpact: {
        speaker: { games: 9, wins: 4, winRate: 44.44 },
        nonSpeaker: { games: 20, wins: 5, winRate: 25.0 },
        deltaWinRate: 19.44,
      },
      aggressionProfile: {
        weights: {
          combatsInitiated: 0.45,
          planetsStolen: 0.35,
          tacticalsWithCombat: 0.2,
        },
        byGame: {
          pbd1732: 7.42,
          pbd1710: 6.88,
          pbd1708: 5.11,
          pbd1684: 8.05,
          pbd1673: 4.74,
          pbd1661: 5.96,
        },
        summary: {
          avgScore: 6.19,
          medianScore: 6.03,
          maxScore: 8.05,
          minScore: 3.82,
          mostAggressiveGameId: "pbd1684",
        },
        coverage: {
          completedGamesConsidered: 29,
          gamesWithRoundStats: 26,
        },
      },
    },
  },
  summary: {
    gamesPlayed: 38,
    activeGames: 7,
    finishedGames: 31,
    abandonedGames: 2,
    wins: 9,
    winPercent: 31.03,
  },
  games: [
    {
      gameId: "pbd1732",
      title: "Cold Equilibrium",
      status: "ACTIVE",
      isActive: true,
      isFinished: false,
      isAbandoned: false,
      createdAtEpochMs: 1769452800000,
      lastUpdatedEpochMs: 1771812100000,
      endedAtEpochMs: null,
      vpTarget: 10,
      round: 5,
      isTiglGame: true,
      tiglMinimumRankAtStart: "TIGL Bronze",
      packs: {
        baseGame: true,
        prophecyOfKings: true,
        discordantStars: false,
        thundersEdge: false,
        thundersEdgeDemo: false,
        twilightsFall: false,
        absol: false,
        miltyMod: true,
        franken: false,
        votc: false,
      },
      gameModes: ["milty_mod", "fog_of_war", "discordant_chat"],
      galacticEvents: {
        eventDeckId: "base",
        inEffect: [
          { eventId: "economic_shock", name: "Economic Shock", instanceId: 2 },
          { eventId: "silent_arms_race", name: "Silent Arms Race", instanceId: 5 },
        ],
      },
      yourSeat: {
        userId: "278901234567890123",
        userName: "JStrong",
        faction: "Mahact",
        color: "orange",
        score: 6,
        eliminated: false,
        passed: true,
        isWinner: false,
        isActivePlayer: false,
        tiglRankAtGameStart: "TIGL Silver",
        diceLuck: { actualHits: 41.0, expectedHits: 39.2, ratio: 1.046 },
      },
      participatingFactionIds: ["Mahact", "Titans of Ul", "Empyrean", "Saar", "Mentak", "Arborec"],
      participatingPlayerNames: ["JStrong", "Ari", "Milo", "Wren", "Helix", "Kira"],
      participants: [
        { userId: "278901234567890123", userName: "JStrong", faction: "Mahact", color: "orange", score: 6, eliminated: false, isWinner: false },
        { userId: "278900000000000001", userName: "Ari", faction: "Titans of Ul", color: "blue", score: 7, eliminated: false, isWinner: false },
        { userId: "278900000000000002", userName: "Milo", faction: "Empyrean", color: "purple", score: 5, eliminated: false, isWinner: false },
        { userId: "278900000000000003", userName: "Wren", faction: "Saar", color: "black", score: 6, eliminated: false, isWinner: false },
        { userId: "278900000000000004", userName: "Helix", faction: "Mentak", color: "yellow", score: 4, eliminated: false, isWinner: false },
        { userId: "278900000000000005", userName: "Kira", faction: "Arborec", color: "green", score: 3, eliminated: false, isWinner: false },
      ],
      actionsJumpUrl: "https://discord.com/channels/123/456/789",
      tableTalkJumpUrl: "https://discord.com/channels/123/456/790",
    },
    {
      gameId: "pbd1708",
      title: "The Last Warrant",
      status: "FINISHED",
      isActive: false,
      isFinished: true,
      isAbandoned: false,
      createdAtEpochMs: 1753833600000,
      lastUpdatedEpochMs: 1763232000000,
      endedAtEpochMs: 1763232000000,
      vpTarget: 10,
      round: 8,
      isTiglGame: true,
      tiglMinimumRankAtStart: "TIGL Silver",
      packs: {
        baseGame: true,
        prophecyOfKings: true,
        discordantStars: true,
        thundersEdge: false,
        thundersEdgeDemo: false,
        twilightsFall: false,
        absol: true,
        miltyMod: false,
        franken: false,
        votc: false,
      },
      gameModes: ["alliance", "absol", "tigl"],
      galacticEvents: {
        eventDeckId: "pok",
        inEffect: [
          { eventId: "stellar_convert", name: "Stellar Conversion", instanceId: 1 },
          { eventId: "supply_shortage", name: "Supply Shortage", instanceId: 3 },
        ],
      },
      yourSeat: {
        userId: "278901234567890123",
        userName: "JStrong",
        faction: "Naalu",
        color: "pink",
        score: 10,
        eliminated: false,
        passed: true,
        isWinner: true,
        isActivePlayer: false,
        tiglRankAtGameStart: "TIGL Silver",
        diceLuck: { actualHits: 73.0, expectedHits: 68.7, ratio: 1.0626 },
      },
      participatingFactionIds: ["Naalu", "L1Z1X", "Ghosts of Creuss", "Mentak", "Yssaril", "Jol-Nar"],
      participatingPlayerNames: ["JStrong", "Maddox", "Iris", "Helix", "Nova", "Rook"],
      participants: [
        { userId: "278901234567890123", userName: "JStrong", faction: "Naalu", color: "pink", score: 10, eliminated: false, isWinner: true },
        { userId: "278900000000000006", userName: "Maddox", faction: "L1Z1X", color: "blue", score: 9, eliminated: false, isWinner: false },
        { userId: "278900000000000007", userName: "Iris", faction: "Ghosts of Creuss", color: "white", score: 8, eliminated: false, isWinner: false },
        { userId: "278900000000000004", userName: "Helix", faction: "Mentak", color: "yellow", score: 6, eliminated: false, isWinner: false },
        { userId: "278900000000000008", userName: "Nova", faction: "Yssaril", color: "green", score: 5, eliminated: false, isWinner: false },
        { userId: "278900000000000009", userName: "Rook", faction: "Jol-Nar", color: "purple", score: 7, eliminated: false, isWinner: false },
      ],
      actionsJumpUrl: "https://discord.com/channels/123/999/111",
      tableTalkJumpUrl: "https://discord.com/channels/123/999/222",
    },
  ],
};
