import type { PlayerData } from "@/data/types";

/**
 * Picks the common set of player fields that multiple PlayerCard variants need
 * to render. Centralizing this prevents each card from repeating the same
 * destructuring logic.
 */
export function getPlayerCardLayoutFields(playerData: PlayerData) {
  const {
    userName,
    faction,
    color,
    tacticalCC,
    fleetCC,
    strategicCC,
    fragments,
    isSpeaker,
    relics,
    planets,
    secretsScored,
    knownUnscoredSecrets,
    leaders,
    scs = [],
    exhaustedSCs,
    passed,
    active,
    neighbors = [],
    tg,
    commodities,
    commoditiesTotal,
    soCount = 0,
    pnCount = 0,
    acCount = 0,
    debtTokens,
    exhaustedRelics,
    nombox,
    exhaustedPlanetAbilities,
    exhaustedPlanets,
    factionTechs,
    abilities,
    plotCards,
    customPromissoryNotes,
    breachTokensReinf,
    galvanizeTokensReinf,
    sleeperTokensReinf,
    ghostWormholesReinf,
  } = playerData;

  return {
    userName,
    faction,
    color,
    tacticalCC,
    fleetCC,
    strategicCC,
    fragments,
    isSpeaker,
    relics,
    planets,
    secretsScored,
    knownUnscoredSecrets,
    leaders,
    scs,
    exhaustedSCs,
    passed,
    active,
    neighbors,
    tg,
    commodities,
    commoditiesTotal,
    soCount,
    pnCount,
    acCount,
    debtTokens,
    exhaustedRelics,
    nombox,
    exhaustedPlanetAbilities,
    exhaustedPlanets,
    factionTechs,
    abilities,
    plotCards,
    customPromissoryNotes,
    breachTokensReinf,
    galvanizeTokensReinf,
    sleeperTokensReinf,
    ghostWormholesReinf,
  };
}

export type PlayerCardLayoutFields = ReturnType<typeof getPlayerCardLayoutFields>;
